### PR TITLE
Use @Observable than conforming to ObservableObject

### PR DESCRIPTION
**Pull request by devahmedshendy**

### CODE REVIEW

**Review by benjaminRoberts01375 — CHANGES_REQUESTED** [review]
Mostly good, however this implementation loses the bindings for translation, scale, and the interaction point. This functionality should be restored before the changes can be approved.

**Comment by devahmedshendy** [comment]
@benjaminRoberts01375 What to read to understand the use/need of `@binding` property in this case, I used to use @Published to trigger view updates when the property changes.

**Comment by benjaminRoberts01375** [comment]
It's honestly not something I've thought about @devahmedshendy, I'll look into it more when I have time available.

**Comment by benjaminRoberts01375** [comment]
@devahmedshendy I'm about to get to sleep, but I had a brain wave. You might be able to use `@ObservationIgnored` on those bindings. I think that'll keep them from being converted to computed properties, thus `@Binding` becomes usable again.

[here are the docs](https://developer.apple.com/documentation/observation/observationignored())

**Comment by devahmedshendy** [comment]
Sorry for the late reply, wasn't able to get back here, Alright, I will test this and see how it works.

**Comment by devahmedshendy** [comment]
I actually thought conforming to `ObservableObject` is the same as use `@Observable` property wrapper. I will recheck that.

**Comment by devahmedshendy** [comment]
@benjaminRoberts01375 I made the changes, but haven't test them yet, will do it later. But we were correct, the `@Binding` becomes usable now.

**Review by benjaminRoberts01375 — APPROVED** [review]

**Pull request merged**
